### ISSUE TITLE
Why pageNumber is saved in UserRepository instead of ListViewModel? (Responsibility distribution doubt between ViewModel and Model.)

### ISSUE THREAD

**Issue by Chintan1193** [iChintanSoni/RepositoryPattern#12]
### Description

I was referring to your implemented Repository Pattern and it is really interesting and useful. Great job! 👍 I have one question (or doubt!) regarding responsibility distribution between ViewModel and Model layers. You have kept `pageNumber` in `UserRepository`, which is a **Model (Data)** layer. I think it should be part of the **ViewModel** layer (`ListViewModel` in this case).

#Reasons:

According to MVVM pattern:

1. Model (Data) layer should be responsible for providing data to ViewModel layer only.
2. ViewModel layer is responsible to persist current state of View (and not Model layer).
3. View can observe ViewModel and ViewModel can observe Model. In this way, Model is independent of ViewModel, which means Model doesn't have any idea of ViewModel's state or even which ViewModel is observing.
4. In your repository pattern, you are storing `pageNumber` at Model layer, which means your Model layer is indirectly keeping state of ViewModel (and ultimately of your View). This conflicts with the MVVM pattern principles, mentioned in previous points.

There must be some reason for why you have kept `pageNumber` at Model layer instead of ViewModel. I would like to know your views on this. 🙂

**Comment by iyashsoni** [comment]
Well, that's a good question. TBH, Point 2 is somewhat misunderstood, the Page number is the state of Model and not View. It is the responsibility of the Model to store its state, which is why pageNumber lies at Model Layer. Hope this clears your confusion.

**Comment by Chintan1193** [comment]
@iyashsoni thank you for the clarification.
